//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppQuanLyBongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_DICHVU
    {
        public int MADICHVU { get; set; }
        public int MAPTT { get; set; }
        public int SOLANSUDUNG { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEUTHANHTOAN PHIEUTHANHTOAN { get; set; }
    }
}
