//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppQuanLyBongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATSAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDATSAN()
        {
            this.CHITIET_PHIEUDATSAN = new HashSet<CHITIET_PHIEUDATSAN>();
        }
    
        public int MAPDS { get; set; }
        public System.DateTime NGAYDATSAN { get; set; }
        public System.DateTime GIODATSAN { get; set; }
        public System.DateTime NGAYLAPPDS { get; set; }
        public int MAKH { get; set; }
        public Nullable<int> MANV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUDATSAN> CHITIET_PHIEUDATSAN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
