//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppQuanLyBongDa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANGSAN
    {
        public int MATINHTRANGSAN { get; set; }
        public Nullable<int> MASAN { get; set; }
        public Nullable<int> MAKHUNGGIO { get; set; }
        public int TRANGTHAI { get; set; }
    
        public virtual GIO GIO { get; set; }
        public virtual SAN SAN { get; set; }
    }
}
